import { defineUtilityNodePack } from "../define-utility-node-pack.ts";

export const sailorCoreUtilityNodePack = defineUtilityNodePack({
  id: "sailor-core",
  name: "Sailor Core",
  description: "Official Sailor utility nodes for workflow control, data, events, forms, and AI.",
  version: "1.0.0",
  nodes: {
    trigger: {
      type: "trigger",
      label: "Trigger",
      description: "Add another workflow entry point.",
      category: "Core",
      style: {
        icon: "zap",
        iconColor: "#facc15",
        bgColor: "#fef9c3",
        borderColor: "#fde047",
      },
    },
    code: {
      type: "code",
      label: "Code Block",
      description: "Run custom JavaScript in a sandbox.",
      category: "Developer",
      style: {
        icon: "code-2",
        iconColor: "#60a5fa",
        bgColor: "#eff6ff",
        borderColor: "#93c5fd",
      },
    },
    http: {
      type: "http",
      label: "HTTP Request",
      description: "Send an HTTP request to an external API.",
      category: "Developer",
      style: {
        icon: "globe",
        iconColor: "#8b5cf6",
        bgColor: "#f5f3ff",
        borderColor: "#c4b5fd",
      },
    },
    if: {
      type: "if",
      label: "If / Else",
      description: "Branch the flow based on a condition.",
      category: "Flow",
      style: {
        icon: "git-branch",
        iconColor: "#f59e0b",
        bgColor: "#fffbeb",
        borderColor: "#fcd34d",
      },
    },
    switch: {
      type: "switch",
      label: "Switch",
      description: "Route to multiple paths based on a value.",
      category: "Flow",
      style: {
        icon: "git-branch-plus",
        iconColor: "#ec4899",
        bgColor: "#fdf2f8",
        borderColor: "#f9a8d4",
      },
    },
    loop: {
      type: "loop",
      label: "Loop / ForEach",
      description: "Iterate over a collection item by item.",
      category: "Flow",
      style: {
        icon: "repeat",
        iconColor: "#34d399",
        bgColor: "#ecfdf5",
        borderColor: "#6ee7b7",
      },
    },
    merge: {
      type: "merge",
      label: "Merge",
      description: "Merge parallel flows into a single path.",
      category: "Flow",
      style: {
        icon: "merge",
        iconColor: "#14b8a6",
        bgColor: "#f0fdfa",
        borderColor: "#5eead4",
      },
    },
    "split-in-batches": {
      type: "split-in-batches",
      label: "Split In Batches",
      description: "Split an array into batches and process each one.",
      category: "Data transformation",
      style: {
        icon: "layers",
        iconColor: "#38bdf8",
        bgColor: "#f0f9ff",
        borderColor: "#7dd3fc",
      },
    },
    set: {
      type: "set",
      label: "Set Fields",
      description: "Set or rename fields without JavaScript.",
      category: "Data transformation",
      style: {
        icon: "sliders-horizontal",
        iconColor: "#a78bfa",
        bgColor: "#f5f3ff",
        borderColor: "#c4b5fd",
      },
    },
    event: {
      type: "event",
      label: "Event Emitter",
      description: "Publish an event to trigger other flows.",
      category: "Core",
      style: {
        icon: "radio",
        iconColor: "#f97316",
        bgColor: "#fff7ed",
        borderColor: "#fdba74",
      },
    },
    "event-listener": {
      type: "event-listener",
      label: "Event Listener",
      description: "Wait for an event to trigger a sub-flow.",
      category: "Flow",
      style: {
        icon: "target",
        iconColor: "#fb7185",
        bgColor: "#fff1f2",
        borderColor: "#fda4af",
      },
    },
    subworkflow: {
      type: "subworkflow",
      label: "Sub-Workflow",
      description: "Call another workflow as a sub-step.",
      category: "Flow",
      style: {
        icon: "layers-3",
        iconColor: "#818cf8",
        bgColor: "#eef2ff",
        borderColor: "#a5b4fc",
      },
    },
    "respond-webhook": {
      type: "respond-webhook",
      label: "Respond to Webhook",
      description: "Respond to the HTTP caller with a custom status and body.",
      category: "Core",
      style: {
        icon: "send",
        iconColor: "#2dd4bf",
        bgColor: "#f0fdfa",
        borderColor: "#5eead4",
      },
    },
    "wait-form": {
      type: "wait-form",
      label: "Wait for Form",
      description: "Create a temporary form and continue after submission.",
      category: "Flow",
      style: {
        icon: "clipboard-list",
        iconColor: "#22c55e",
        bgColor: "#f0fdf4",
        borderColor: "#86efac",
      },
    },
    "ai-agent": {
      type: "ai-agent",
      label: "AI Agent",
      description: "Run a governed agent with tools and memory.",
      category: "AI",
      style: {
        icon: "bot",
        iconColor: "#f97316",
        bgColor: "#fff7ed",
        borderColor: "#fdba74",
      },
    },
    "ai-model": {
      type: "ai-model",
      label: "AI Model",
      description: "Attach a chat model configuration to an AI Agent.",
      category: "AI",
      style: {
        icon: "brain",
        iconColor: "#8b5cf6",
        bgColor: "#f5f3ff",
        borderColor: "#c4b5fd",
      },
    },
    "ai-memory": {
      type: "ai-memory",
      label: "AI Memory",
      description: "Attach a memory store configuration to an AI Agent.",
      category: "AI",
      style: {
        icon: "database",
        iconColor: "#06b6d4",
        bgColor: "#ecfeff",
        borderColor: "#67e8f9",
      },
    },
    "ai-tool": {
      type: "ai-tool",
      label: "AI Tool",
      description: "Attach a callable tool configuration to an AI Agent.",
      category: "AI",
      style: {
        icon: "wrench",
        iconColor: "#64748b",
        bgColor: "#f8fafc",
        borderColor: "#cbd5e1",
      },
    },
    "text-dataset": {
      type: "text-dataset",
      label: "Text Dataset",
      description: "Load text or JSON items as reusable workflow data.",
      category: "Data transformation",
      style: {
        icon: "text",
        iconColor: "#0f766e",
        bgColor: "#f0fdfa",
        borderColor: "#5eead4",
      },
    },
    "file-dataset": {
      type: "file-dataset",
      label: "File Dataset",
      description: "Load TXT, Markdown, JSON, or CSV files as workflow data.",
      category: "Data transformation",
      style: {
        icon: "file-text",
        iconColor: "#2563eb",
        bgColor: "#eff6ff",
        borderColor: "#93c5fd",
      },
    },
    "database-dataset": {
      type: "database-dataset",
      label: "Database Dataset",
      description: "Load database rows through a provider plugin as workflow data.",
      category: "Data transformation",
      style: {
        icon: "table-2",
        iconColor: "#7c3aed",
        bgColor: "#f5f3ff",
        borderColor: "#c4b5fd",
      },
    },
    embeddings: {
      type: "embeddings",
      label: "Embeddings",
      description: "Create vectors from dataset items through an embedding provider plugin.",
      category: "AI",
      style: {
        icon: "scan-text",
        iconColor: "#db2777",
        bgColor: "#fdf2f8",
        borderColor: "#f9a8d4",
      },
    },
    "vector-store": {
      type: "vector-store",
      label: "Vector Store",
      description: "Configure a provider-backed vector collection for indexing and search.",
      category: "AI",
      style: {
        icon: "database-zap",
        iconColor: "#0891b2",
        bgColor: "#ecfeff",
        borderColor: "#67e8f9",
      },
    },
    retriever: {
      type: "retriever",
      label: "Retriever",
      description: "Retrieve relevant context from a configured vector store.",
      category: "AI",
      style: {
        icon: "search",
        iconColor: "#65a30d",
        bgColor: "#f7fee7",
        borderColor: "#bef264",
      },
    },
  },
});
