// ─────────────────────────────────────────────────────────────
//  API Client (Fetch Wrapper)
// ─────────────────────────────────────────────────────────────

import { API_BASE_URL } from '../constants/app'
import { ApiError, type ApiResponse } from '../types/api.types'

export interface RequestOptions extends Omit<RequestInit, 'body'> {
  body?: unknown
  params?: Record<string, string | number | boolean | undefined>
}

/**
 * Builds a URL with search params.
 */
function buildUrl(
  path: string,
  params?: Record<string, string | number | boolean | undefined>,
): string {
  const baseUrl = API_BASE_URL || (typeof window !== 'undefined' ? window.location.origin : 'http://localhost')
  const url = new URL(`${API_BASE_URL}${path}`, baseUrl)

  if (params) {
    Object.entries(params).forEach(([key, value]) => {
      if (value !== undefined && value !== null) {
        url.searchParams.append(key, String(value))
      }
    })
  }

  return url.toString()
}

/**
 * Core API request function.
 * Normalizes responses to throw ApiError on failures.
 */
export async function apiRequest<T>(path: string, options: RequestOptions = {}): Promise<T> {
  const { body, params, headers, ...restOptions } = options

  const url = buildUrl(path, params)

  const reqHeaders = new Headers(headers as HeadersInit)

  // Auto-set Content-Type for JSON objects
  if (body && !(body instanceof FormData) && typeof body === 'object') {
    if (!reqHeaders.has('Content-Type')) {
      reqHeaders.set('Content-Type', 'application/json')
    }
  }

  // Support taking an execution-id generated by the client
  // (Not typical for fetch, but if headers contain it, keep it)

  const fetchOptions: RequestInit = {
    ...restOptions,
    headers: reqHeaders,
    body: body instanceof FormData ? body : body ? JSON.stringify(body) : undefined,
  }

  let response: Response
  try {
    response = await fetch(url, fetchOptions)
  } catch (error) {
    throw new ApiError(
      'Network request failed',
      0,
      error instanceof Error ? error.message : String(error),
    )
  }

  // Handle No Content
  if (response.status === 204) {
    return null as T
  }

  let data: ApiResponse<T>
  try {
    data = await response.json()
  } catch (err) {
    // If it's not JSON but the request was OK, maybe it was a raw response?
    // In Fabric, we expect our standard ApiResponse envelope.
    if (!response.ok) {
      throw new ApiError(`HTTP Error ${response.status}: ${response.statusText}`, response.status)
    }
    throw new ApiError('Failed to parse response as JSON', response.status)
  }

  // API Envelope Error
  if (!response.ok || data.error || data.status_code >= 400) {
    const message = data.message ?? 'Request failed'
    const detail = data.error ?? null

    throw new ApiError(
      detail && detail !== message ? `${message}: ${detail}` : message,
      data.status_code ?? response.status,
      detail,
    )
  }

  return data.data as T
}
