import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

import { validateManifest } from "../plugins/loader.ts";
import type { ProfilePaths } from "../../profiles/profile-paths.ts";
import { parsePluginBlueprint } from "./plugin-blueprint-validation.ts";
import type { PluginBlueprint } from "./plugin-blueprint-types.ts";
import { resolveBlueprintPaths } from "./plugin-creator-paths.ts";
import { generatePluginManifest } from "./plugin-manifest-generator.ts";
import { generatePluginAuthProvider } from "./plugin-manifest-generator.ts";
import { generatePluginMethodsSource } from "./plugin-methods-generator.ts";

export interface GenerateCompletePluginInput {
  profilePaths: ProfilePaths;
  blueprint: PluginBlueprint;
  creatorVersion?: string;
}

export interface GeneratedPluginFile {
  relativePath: string;
  absolutePath: string;
  content?: string;
}

export interface GeneratedCompletePlugin {
  generatedDir: string;
  files: GeneratedPluginFile[];
}

const helperFiles = [
  "plugin-request-template.ts",
  "plugin-response-mapper.ts",
  "plugin-error-mapper.ts",
  "plugin-generated-http-helpers.ts",
] as const;

export function generateCompletePlugin(input: GenerateCompletePluginInput): GeneratedCompletePlugin {
  const blueprint = parsePluginBlueprint(input.blueprint);
  const paths = resolveBlueprintPaths(input.profilePaths, blueprint.id);
  const manifest = generatePluginManifest(blueprint, { creatorVersion: input.creatorVersion });
  const manifestErrors = validateManifest(manifest);

  if (manifestErrors.length > 0) {
    throw new Error(`Generated plugin manifest is invalid: ${manifestErrors.join("; ")}`);
  }

  fs.rmSync(paths.generatedDir, { recursive: true, force: true });
  fs.mkdirSync(paths.generatedDir, { recursive: true });

  const files: GeneratedPluginFile[] = [];

  writeGeneratedFile(files, paths.generatedDir, "manifest.json", `${JSON.stringify(manifest, null, 2)}\n`);
  const methodsSource = generatePluginMethodsSource(blueprint);
  writeGeneratedFile(files, paths.generatedDir, "methods.ts", methodsSource);
  writeGeneratedFile(files, paths.generatedDir, "methods.js", transpileTypescript(methodsSource));
  writeGeneratedFile(files, paths.generatedDir, "index.ts", generateIndexSource());
  writeGeneratedFile(files, paths.generatedDir, "index.js", generateRuntimeIndexSource(blueprint));
  writeGeneratedFile(files, paths.generatedDir, "package.json", `${JSON.stringify(generatePackageJson(blueprint), null, 2)}\n`);
  writeGeneratedFile(files, paths.generatedDir, "package-lock.json", `${JSON.stringify(generatePackageLockJson(blueprint), null, 2)}\n`);
  writeGeneratedFile(files, paths.generatedDir, "README.md", generateReadme(blueprint));

  for (const helperFile of helperFiles) {
    const sourcePath = path.join(currentDir(), helperFile);
    copyGeneratedFile(files, sourcePath, paths.generatedDir, helperFile);
    writeGeneratedFile(
      files,
      paths.generatedDir,
      helperFile.replace(/\.ts$/, ".js"),
      transpileTypescript(fs.readFileSync(sourcePath, "utf8")),
    );
  }

  copyIconAssets(files, paths.assetsDir, paths.generatedDir, blueprint);

  return {
    generatedDir: paths.generatedDir,
    files,
  };
}

function generateIndexSource(): string {
  return `export { methods } from "./methods.js";
`;
}

function generateRuntimeIndexSource(blueprint: PluginBlueprint): string {
  return `import { methods } from "./methods.js";

const manifest = ${JSON.stringify(generatePluginManifest(blueprint), null, 2)};
const auth = ${JSON.stringify(generatePluginAuthProvider(blueprint), null, 2)};

const plugin = {
  id: manifest.metadata.id,
  manifest,
  auth,
  methods,
};

export default plugin;
`;
}

function generatePackageJson(blueprint: PluginBlueprint): Record<string, unknown> {
  return {
    name: `@sailor-generated/${blueprint.metadata.handle}`,
    version: blueprint.metadata.version,
    description: blueprint.metadata.description,
    type: "module",
    main: "index.js",
    dependencies: {
      "@auvexis/sailor-sdk": "^1.2.0",
    },
    devDependencies: {
      typescript: "^5.9.3",
    },
  };
}

function generatePackageLockJson(blueprint: PluginBlueprint): Record<string, unknown> {
  return {
    name: `@sailor-generated/${blueprint.metadata.handle}`,
    version: blueprint.metadata.version,
    lockfileVersion: 3,
    requires: true,
    packages: {
      "": generatePackageJson(blueprint),
    },
  };
}

function generateReadme(blueprint: PluginBlueprint): string {
  const methodList = blueprint.methods
    .map((method) => `- \`${method.handle}\`: ${method.description}`)
    .join("\n");

  return `# ${blueprint.metadata.name}

${blueprint.metadata.description}

Generated by Sailor Plugin Creator.

## Methods

${methodList || "- No methods generated."}
`;
}

function copyIconAssets(
  files: GeneratedPluginFile[],
  sourceAssetsDir: string,
  generatedDir: string,
  blueprint: PluginBlueprint,
): void {
  const iconPaths = [blueprint.icons.icon, blueprint.icons.iconDark, blueprint.icons.iconLight]
    .filter((icon): icon is string => Boolean(icon));

  for (const iconPath of new Set(iconPaths)) {
    if (!isLocalIconAssetPath(iconPath)) continue;

    const normalizedIconPath = iconPath.replaceAll("\\", "/");
    const sourceRelativePath = normalizedIconPath.startsWith("assets/")
      ? normalizedIconPath.slice("assets/".length)
      : normalizedIconPath;
    const sourcePath = path.join(sourceAssetsDir, sourceRelativePath);
    if (!fs.existsSync(sourcePath)) continue;

    copyGeneratedFile(files, sourcePath, generatedDir, path.join("assets", sourceRelativePath));
  }
}

function isLocalIconAssetPath(iconPath: string): boolean {
  const normalized = iconPath.toLowerCase();
  return !(
    normalized.startsWith("http://") ||
    normalized.startsWith("https://") ||
    normalized.startsWith("data:image/")
  );
}

function writeGeneratedFile(
  files: GeneratedPluginFile[],
  generatedDir: string,
  relativePath: string,
  content: string,
): void {
  const absolutePath = path.join(generatedDir, relativePath);
  fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
  fs.writeFileSync(absolutePath, content, "utf8");
  files.push({ relativePath: normalizeRelativePath(relativePath), absolutePath, content });
}

function copyGeneratedFile(
  files: GeneratedPluginFile[],
  sourcePath: string,
  generatedDir: string,
  relativePath: string,
): void {
  const absolutePath = path.join(generatedDir, relativePath);
  fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
  fs.copyFileSync(sourcePath, absolutePath);
  files.push({ relativePath: normalizeRelativePath(relativePath), absolutePath });
}

function normalizeRelativePath(relativePath: string): string {
  return relativePath.replaceAll(path.sep, "/");
}

function currentDir(): string {
  return path.dirname(fileURLToPath(import.meta.url));
}

function transpileTypescript(source: string): string {
  return ts.transpileModule(source, {
    compilerOptions: {
      module: ts.ModuleKind.ES2022,
      target: ts.ScriptTarget.ES2022,
      moduleResolution: ts.ModuleResolutionKind.NodeNext,
      verbatimModuleSyntax: true,
    },
  }).outputText;
}
