import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, it } from "node:test";

import { resolveProfilePaths } from "../../profiles/profile-paths.ts";
import { generateCompletePlugin } from "./plugin-code-generator.ts";
import type { PluginBlueprint } from "./plugin-blueprint-types.ts";

function createBlueprint(): PluginBlueprint {
  return {
    id: "bp_my_crm",
    metadata: {
      handle: "my-crm",
      name: "My CRM",
      version: "0.1.0",
      description: "CRM API connector",
    },
    icons: {
      icon: "icon.svg",
      iconDark: "icon-dark.svg",
      iconLight: "icon-light.svg",
    },
    auth: {
      type: "apiKey",
      fields: [
        {
          name: "apiKey",
          label: "API Key",
          target: "header",
          headerName: "Authorization",
          prefix: "Bearer ",
        },
      ],
    },
    methods: [
      {
        id: "method_create_lead",
        handle: "createLead",
        name: "Create Lead",
        description: "Create a CRM lead",
        inputs: [
          {
            name: "email",
            type: "string",
            required: true,
            description: "Lead email",
          },
        ],
        request: {
          method: "POST",
          url: "https://api.example.com/leads",
          headers: [{ name: "Authorization", value: "Bearer {{ credentials.apiKey }}" }],
          query: [],
          body: { type: "json", value: { email: "{{ params.email }}" } },
        },
        responseMapping: [
          {
            id: "map_lead_id",
            outputName: "leadId",
            path: "body.data.id",
            type: "string",
            required: true,
          },
        ],
        errorMapping: [],
      },
    ],
    canvas: { nodes: {}, edges: [] },
    createdAt: "2026-05-20T00:00:00.000Z",
    updatedAt: "2026-05-20T00:00:00.000Z",
  };
}

function createProfilePaths() {
  const sailorHome = fs.mkdtempSync(path.join(os.tmpdir(), "sailor-plugin-code-generator-"));
  return resolveProfilePaths({ sailorHome, profileId: "default" });
}

describe("generateCompletePlugin", () => {
  it("writes a complete generated plugin under the blueprint generated directory", () => {
    const profilePaths = createProfilePaths();
    const blueprint = createBlueprint();
    const assetsDir = path.join(
      profilePaths.profileDir,
      "plugin-creator",
      "blueprints",
      blueprint.id,
      "assets",
    );
    fs.mkdirSync(assetsDir, { recursive: true });
    fs.writeFileSync(path.join(assetsDir, "icon.svg"), "<svg>icon</svg>\n", "utf8");
    fs.writeFileSync(path.join(assetsDir, "icon-dark.svg"), "<svg>dark</svg>\n", "utf8");
    fs.writeFileSync(path.join(assetsDir, "icon-light.svg"), "<svg>light</svg>\n", "utf8");

    const result = generateCompletePlugin({ profilePaths, blueprint, creatorVersion: "1.0.0" });

    assert.equal(
      result.generatedDir,
      path.join(profilePaths.profileDir, "plugin-creator", "blueprints", "bp_my_crm", "generated"),
    );
    assert.deepEqual(
      result.files.map((file) => file.relativePath).sort(),
      [
        "README.md",
        "assets/icon-dark.svg",
        "assets/icon-light.svg",
        "assets/icon.svg",
        "index.ts",
        "manifest.json",
        "package.json",
        "plugin-error-mapper.ts",
        "plugin-generated-http-helpers.ts",
        "plugin-request-template.ts",
        "plugin-response-mapper.ts",
        "methods.ts",
      ].sort(),
    );

    const manifest = JSON.parse(fs.readFileSync(path.join(result.generatedDir, "manifest.json"), "utf8"));
    assert.equal(manifest.metadata.id, "my-crm");
    assert.equal(manifest["x-created-by"], "sailor-plugin-creator");
    assert.equal(manifest["x-creator-version"], "1.0.0");
    assert.equal(manifest["x-editable-low-code"], true);

    const methodsSource = fs.readFileSync(path.join(result.generatedDir, "methods.ts"), "utf8");
    assert.match(methodsSource, /export const methods = \{/);
    assert.match(methodsSource, /createLead/);

    const indexSource = fs.readFileSync(path.join(result.generatedDir, "index.ts"), "utf8");
    assert.match(indexSource, /export \{ methods \} from "\.\/methods\.js";/);

    const packageJson = JSON.parse(fs.readFileSync(path.join(result.generatedDir, "package.json"), "utf8"));
    assert.equal(packageJson.name, "@sailor-generated/my-crm");
    assert.equal(packageJson.version, "0.1.0");
    assert.equal(packageJson.dependencies["@auvexis/sailor-sdk"], "^1.2.0");

    const readme = fs.readFileSync(path.join(result.generatedDir, "README.md"), "utf8");
    assert.match(readme, /# My CRM/);
    assert.match(readme, /Generated by Sailor Plugin Creator/);

    assert.equal(fs.readFileSync(path.join(result.generatedDir, "assets", "icon.svg"), "utf8"), "<svg>icon</svg>\n");
  });
});
