import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import test from 'node:test'

const root = resolve(import.meta.dirname, '../../../../..')

function read(relativePath: string): string {
  return readFileSync(resolve(root, relativePath), 'utf8')
}

test('workflow editor renders inside the shared workbench shell', () => {
  const source = read('src/app/pages/WorkflowEditorPage.vue')

  assert.match(source, /AppWorkbench/)
  assert.match(source, /:show-global-panel="false"/)
  assert.match(source, /GlobalAppPanel/)
  assert.match(source, /WorkbenchStatusBar/)
  assert.doesNotMatch(source, /#toolstrip/)
  assert.match(source, /#left/)
  assert.match(source, /#status/)
  assert.match(source, /BaseRail/)
  assert.match(source, /BaseRailItem/)
  assert.match(source, /BaseRailButtonToggleItem/)
  assert.doesNotMatch(source, /Create git snapshot"[\s\S]{0,140}workflow-tool-rail__button--active/)
  assert.doesNotMatch(source, /workflow-status-bar__button--git"\s*:class="\{ 'workflow-status-bar__button--active'/)
  assert.match(source, /workflow-workbench__canvas/)
  assert.match(source, /<AppPanel[\s\S]*class="workflow-inspector-panel"/)
  assert.match(source, /const showInspector = ref\(true\)/)
  assert.match(source, /:is-open="showInspector"/)
  assert.match(source, /@close="showInspector = false"/)
  assert.doesNotMatch(source, /title="Open workflow settings"/)
  assert.match(source, /workflow-inspector-panel/)
  assert.match(source, /workflow-inspector-width/)
  assert.match(source, /workflow-side-panel-width/)
  assert.match(source, /workflow-global-panel-width/)
  assert.match(source, /globalSidePanelWidth/)
  assert.match(source, /workflow-bottom-panel-right/)
  assert.match(source, /workflow-canvas-right/)
  assert.match(source, /workflow-canvas-bottom/)
  assert.match(source, /workflow-workbench__canvas-viewport/)
  assert.match(source, /workflowWorkbenchStyle/)
  assert.match(source, /handleInspectorPanelResize/)
  assert.match(source, /handleSettingsPanelResize/)
  assert.match(source, /startBottomPanelResize/)
  assert.match(source, /closeGlobalSidePanel/)
  assert.match(source, /app-panel--right:not\(\.workflow-inspector-panel\)/)
  assert.match(source, /workflow-workbench__bottom-panel/)
  assert.match(source, /@close="isBottomPanelOpen = false"/)
  assert.match(source, /useNodeInspectorStore/)
  assert.match(source, /activeInspectorNodeEdges/)
  assert.match(source, /workflowRuntimeState/)
  assert.match(source, />\s*Routing\s*</)
  assert.match(source, />\s*Runtime\s*</)
  assert.doesNotMatch(source, /Duplicate\s*<\/button>/)
  assert.doesNotMatch(source, /Delete\s*<\/button>/)
  assert.match(source, /openGlobalAddNodePanel/)
  assert.match(source, /canvasRef\?\.handleRun/)
})

test('workbench components expose toolstrip body and status slots', () => {
  const workbench = read('src/shared/components/workbench/AppWorkbench.vue')
  const status = read('src/shared/components/workbench/WorkbenchStatusBar.vue')
  const bottomPanel = read('src/shared/components/workbench/WorkbenchBottomPanel.vue')
  const appPage = read('src/shared/components/layout/AppPage.vue')
  const appShell = read('src/shared/components/layout/AppShell.vue')

  assert.match(workbench, /app-workbench__toolstrip/)
  assert.match(workbench, /app-workbench__main/)
  assert.match(workbench, /app-workbench__status/)
  assert.match(workbench, /app-workbench--has-toolstrip/)
  assert.match(workbench, /app-workbench--has-status/)
  assert.match(workbench, /grid-template-rows: minmax\(0, 1fr\) var\(--fabric-workbench-status-height, 24px\)/)
  assert.match(workbench, /height: var\(--fabric-workbench-status-height, 24px\)/)
  assert.match(workbench, /max-height: var\(--fabric-workbench-status-height, 24px\)/)
  assert.match(appPage, /\.app-page__content:has\(> \.app-workbench\)/)
  assert.match(appShell, /min-height: 0;/)
  assert.match(status, /workbench-status-bar__zone--left/)
  assert.match(status, /workbench-status-bar__zone--right/)
  assert.match(status, /display: flex;/)
  assert.doesNotMatch(status, /grid-template-columns/)
  assert.match(bottomPanel, /workbench-bottom-panel/)
  assert.match(bottomPanel, /workbench-bottom-panel__resize/)
  assert.match(bottomPanel, /workbench-bottom-panel__header/)
  assert.match(bottomPanel, /workbench-bottom-panel__close/)
  assert.match(bottomPanel, /resize-start/)
  assert.match(bottomPanel, /close: \[\]/)
  assert.match(bottomPanel, /var\(--fabric-workbench-border\)/)
})

test('fabric themes define workbench tokens', () => {
  const light = JSON.parse(read('src/themes/json/light.json'))
  const dark = JSON.parse(read('src/themes/json/dark.json'))

  for (const theme of [light, dark]) {
    assert.equal(typeof theme.tokens['workbench.bg'], 'string')
    assert.equal(typeof theme.tokens['workbench.main.bg'], 'string')
    assert.equal(typeof theme.tokens['workbench.status.bg'], 'string')
    assert.equal(typeof theme.tokens['workbench.panel.header.bg'], 'string')
    assert.equal(typeof theme.tokens['workbench.rail.button.hover.bg'], 'string')
    assert.equal(typeof theme.tokens['workflowTimeline.bg'], 'string')
    assert.equal(typeof theme.tokens['workflowTimeline.clip.bg'], 'string')
    assert.equal(typeof theme.tokens['executionPanel.bg'], 'string')
    assert.equal(typeof theme.tokens['globalAddNodePanel.bg'], 'string')
    assert.equal(typeof theme.tokens['baseCanvas.bg'], 'string')
    assert.equal(typeof theme.tokens['baseCanvas.grid'], 'string')
    assert.equal(typeof theme.tokens['baseCanvas.ruler.lines'], 'string')
    assert.equal(typeof theme.tokens['baseCanvas.ruler.z'], 'string')
    assert.equal(typeof theme.tokens['baseCanvas.selection.bg'], 'string')
    assert.equal(typeof theme.tokens['baseCanvas.selection.border'], 'string')
    assert.equal(typeof theme.tokens['baseCanvas.alignmentGuide.bg'], 'string')
    assert.equal(typeof theme.tokens['baseCanvas.alignmentGuide.shadow'], 'string')
    assert.equal(typeof theme.tokens['workflowNode.bg'], 'string')
    assert.equal(typeof theme.tokens['workflowNode.border'], 'string')
    assert.equal(typeof theme.tokens['workflowNode.selected.border'], 'string')
    assert.equal(typeof theme.tokens['workflowHandle.bg'], 'string')
    assert.equal(typeof theme.tokens['workflowHandle.hover.bg'], 'string')
    assert.equal(typeof theme.tokens['workflowEdge.stroke'], 'string')
    assert.equal(typeof theme.tokens['workflowEdge.selected'], 'string')
    assert.equal(typeof theme.tokens['workflowEdge.toolbar.bg'], 'string')
    assert.equal(typeof theme.tokens['workflowEdge.label.bg'], 'string')
    assert.equal(typeof theme.tokens['node.body'], 'string')
    assert.equal(typeof theme.tokens['rf.edge.stroke'], 'string')
  }
})
