import { defineUtilityNodePack } from "../define-utility-node-pack.ts";

export const fabricCoreUtilityNodePack = defineUtilityNodePack({
  id: "fabric-core",
  name: "Fabric Core",
  description: "Official Fabric utility nodes for workflow control, data, events, forms, and AI.",
  version: "1.0.0",
  nodes: {
    trigger: {
      type: "trigger",
      label: "Trigger",
      description: "Add another workflow entry point.",
      category: "Core",
      style: {
        icon: "zap",
        iconColor: "var(--fabric-text-primary)",
        bgColor: "var(--fabric-node-body)",
        borderColor: "var(--fabric-node-border)",
      },
    },
    code: {
      type: "code",
      label: "Code Block",
      description: "Run custom JavaScript in a sandbox.",
      category: "Developer",
      style: {
        icon: "code-2",
        iconColor: "var(--fabric-node-codeblock-icon)",
        bgColor: "var(--fabric-node-codeblock-bg)",
        borderColor: "var(--fabric-node-codeblock-border)",
      },
    },
    http: {
      type: "http",
      label: "HTTP Request",
      description: "Send an HTTP request to an external API.",
      category: "Developer",
      style: {
        icon: "globe",
        iconColor: "var(--fabric-node-http-icon)",
        bgColor: "var(--fabric-node-http-bg)",
        borderColor: "var(--fabric-node-http-border)",
      },
    },
    if: {
      type: "if",
      label: "If / Else",
      description: "Branch the flow based on a condition.",
      category: "Flow",
      style: {
        icon: "git-branch",
        iconColor: "var(--fabric-node-if-icon)",
        bgColor: "var(--fabric-node-if-bg)",
        borderColor: "var(--fabric-node-if-border)",
      },
    },
    switch: {
      type: "switch",
      label: "Switch",
      description: "Route to multiple paths based on a value.",
      category: "Flow",
      style: {
        icon: "git-branch-plus",
        iconColor: "var(--fabric-node-switch-icon)",
        bgColor: "var(--fabric-node-switch-bg)",
        borderColor: "var(--fabric-node-switch-border)",
      },
    },
    loop: {
      type: "loop",
      label: "Loop / ForEach",
      description: "Iterate over a collection item by item.",
      category: "Flow",
      style: {
        icon: "repeat",
        iconColor: "var(--fabric-node-loop-icon)",
        bgColor: "var(--fabric-node-loop-bg)",
        borderColor: "var(--fabric-node-loop-border)",
      },
    },
    merge: {
      type: "merge",
      label: "Merge",
      description: "Merge parallel flows into a single path.",
      category: "Flow",
      style: {
        icon: "merge",
        iconColor: "var(--fabric-node-merge-icon)",
        bgColor: "var(--fabric-node-merge-bg)",
        borderColor: "var(--fabric-node-merge-border)",
      },
    },
    "split-in-batches": {
      type: "split-in-batches",
      label: "Split In Batches",
      description: "Split an array into batches and process each one.",
      category: "Data transformation",
      style: {
        icon: "layers",
        iconColor: "var(--fabric-node-split-icon)",
        bgColor: "var(--fabric-node-split-bg)",
        borderColor: "var(--fabric-node-split-border)",
      },
    },
    set: {
      type: "set",
      label: "Set Fields",
      description: "Set or rename fields without JavaScript.",
      category: "Data transformation",
      style: {
        icon: "sliders-horizontal",
        iconColor: "var(--fabric-node-set-icon)",
        bgColor: "var(--fabric-node-set-bg)",
        borderColor: "var(--fabric-node-set-border)",
      },
    },
    event: {
      type: "event",
      label: "Event Emitter",
      description: "Publish an event to trigger other flows.",
      category: "Core",
      style: {
        icon: "radio",
        iconColor: "var(--fabric-node-event-icon)",
        bgColor: "var(--fabric-node-event-bg)",
        borderColor: "var(--fabric-node-event-border)",
      },
    },
    "event-listener": {
      type: "event-listener",
      label: "Event Listener",
      description: "Wait for an event to trigger a sub-flow.",
      category: "Flow",
      style: {
        icon: "target",
        iconColor: "var(--fabric-node-event-listener-icon)",
        bgColor: "var(--fabric-node-event-listener-bg)",
        borderColor: "var(--fabric-node-event-listener-border)",
      },
    },
    "call-workflow": {
      type: "call-workflow",
      label: "Call Workflow",
      description: "Call a published workflow through a callable trigger.",
      category: "Flow",
      capabilities: ["agent-tool"],
      handles: [
        { id: "target", label: "", type: "target", position: "left" },
        { id: "source", label: "", type: "source", position: "right" },
      ],
      style: {
        icon: "workflow",
        iconColor: "var(--fabric-node-call-workflow-icon)",
        bgColor: "var(--fabric-node-call-workflow-bg)",
        borderColor: "var(--fabric-node-call-workflow-border)",
      },
    },
    return: {
      type: "return",
      label: "Return",
      description: "Stop the workflow and expose a final result.",
      category: "Flow",
      handles: [
        { id: "target", label: "", type: "target", position: "left" },
      ],
      style: {
        icon: "corner-down-left",
        iconColor: "var(--fabric-node-return-icon)",
        bgColor: "var(--fabric-node-return-bg)",
        borderColor: "var(--fabric-node-return-border)",
      },
    },
    "respond-webhook": {
      type: "respond-webhook",
      label: "Respond to Webhook",
      description: "Respond to the HTTP caller with a custom status and body.",
      category: "Core",
      style: {
        icon: "send",
        iconColor: "var(--fabric-node-respond-webhook-icon)",
        bgColor: "var(--fabric-node-respond-webhook-bg)",
        borderColor: "var(--fabric-node-respond-webhook-border)",
      },
    },
    "wait-form": {
      type: "wait-form",
      label: "Wait for Form",
      description: "Create a temporary form and continue after submission.",
      category: "Flow",
      style: {
        icon: "clipboard-list",
        iconColor: "#22c55e",
        bgColor: "rgba(34, 197, 94, 0.12)",
        borderColor: "rgba(34, 197, 94, 0.35)",
      },
    },
    "ai-agent": {
      type: "ai-agent",
      label: "AI Agent",
      description: "Run a governed agent with tools and memory.",
      category: "AI",
      presentation: { base: "advanced", autoOrganize: true },
      handles: [
        { id: "chatModel", label: "Chat Model", type: "target", position: "bottom", style: "diamond", required: true, accepts: [{ capability: "chat-model" }], cardinality: "one", connectionPolicy: "replace", quickAdd: "capability", quickAddAfterConnected: false },
        { id: "memory", label: "Memory", type: "target", position: "bottom", style: "diamond", required: false, accepts: [{ capability: "memory-store" }], cardinality: "one", connectionPolicy: "replace", quickAdd: "capability", quickAddAfterConnected: false },
        { id: "tool", label: "Tool", type: "target", position: "bottom", style: "diamond", required: false, accepts: [{ capability: "agent-tool" }], cardinality: "many", connectionPolicy: "append", quickAdd: "capability", quickAddAfterConnected: true },
      ],
      style: {
        icon: "bot",
        iconColor: "var(--fabric-text-muted)",
        bgColor: "transparent",
        borderColor: "var(--fabric-node-border)",
      },
    },
    "ai-model": {
      type: "ai-model",
      label: "AI Model",
      description: "Attach a chat model configuration to an AI Agent.",
      category: "AI",
      role: "configuration",
      capabilities: ["chat-model"],
      presentation: { base: "standard", rounded: "full" },
      handles: [{ id: "source", label: "", type: "source", position: "top", style: "diamond" }],
      style: {
        icon: "brain",
        iconColor: "#8b5cf6",
        bgColor: "#f5f3ff",
        borderColor: "#c4b5fd",
      },
    },
    "ai-memory": {
      type: "ai-memory",
      label: "AI Memory",
      description: "Attach a memory store configuration to an AI Agent.",
      category: "AI",
      role: "configuration",
      capabilities: ["memory-store"],
      presentation: { base: "standard", rounded: "full" },
      handles: [{ id: "source", label: "", type: "source", position: "top", style: "diamond" }],
      style: {
        icon: "database",
        iconColor: "#06b6d4",
        bgColor: "#ecfeff",
        borderColor: "#67e8f9",
      },
    },
    "ai-tool": {
      type: "ai-tool",
      label: "AI Tool",
      description: "Attach a callable tool configuration to an AI Agent.",
      category: "AI",
      role: "configuration",
      capabilities: ["agent-tool"],
      presentation: { base: "standard", rounded: "full" },
      handles: [{ id: "source", label: "", type: "source", position: "top", style: "diamond" }],
      style: {
        icon: "wrench",
        iconColor: "#64748b",
        bgColor: "#f8fafc",
        borderColor: "#cbd5e1",
      },
    },
    "text-dataset": {
      type: "text-dataset",
      label: "Text Dataset",
      description: "Load text or JSON items as reusable workflow data.",
      category: "Data transformation",
      role: "configuration",
      capabilities: ["document-source"],
      presentation: { base: "standard", rounded: "full" },
      handles: [{ id: "source", label: "", type: "source", position: "top", style: "diamond" }],
      style: {
        icon: "text",
        iconColor: "#0f766e",
        bgColor: "#f0fdfa",
        borderColor: "#5eead4",
      },
    },
    "file-dataset": {
      type: "file-dataset",
      label: "Extract From File",
      description: "Extract TXT, Markdown, JSON, or CSV files as structured workflow data.",
      category: "Data transformation",
      role: "configuration",
      capabilities: ["file-data-source", "document-source"],
      presentation: { base: "standard", rounded: "full" },
      handles: [{ id: "source", label: "", type: "source", position: "top", style: "diamond" }],
      style: {
        icon: "file-text",
        iconColor: "#2563eb",
        bgColor: "#eff6ff",
        borderColor: "#93c5fd",
      },
    },
    "database-dataset": {
      type: "database-dataset",
      label: "Database Dataset",
      description: "Load database rows through a provider plugin as workflow data.",
      category: "Data transformation",
      role: "configuration",
      capabilities: ["document-source"],
      presentation: { base: "standard", rounded: "full" },
      handles: [{ id: "source", label: "", type: "source", position: "top", style: "diamond" }],
      style: {
        icon: "table-2",
        iconColor: "#7c3aed",
        bgColor: "#f5f3ff",
        borderColor: "#c4b5fd",
      },
    },
    embeddings: {
      type: "embeddings",
      label: "Embeddings",
      description: "Create vectors from dataset items through an embedding provider plugin.",
      category: "AI",
      role: "configuration",
      capabilities: ["embedding-model"],
      presentation: { base: "standard", rounded: "full" },
      handles: [{ id: "source", label: "", type: "source", position: "top", style: "diamond" }],
      style: {
        icon: "scan-text",
        iconColor: "#db2777",
        bgColor: "#fdf2f8",
        borderColor: "#f9a8d4",
      },
    },
    "vector-store": {
      type: "vector-store",
      label: "Vector Store",
      description: "Configure a provider-backed vector collection for indexing and search.",
      category: "AI",
      capabilities: ["vector-store"],
      presentation: { base: "advanced", autoOrganize: true },
      handles: [
        { id: "embedding", label: "Embedding", type: "target", position: "bottom", style: "diamond", required: true, accepts: [{ capability: "embedding-model" }], cardinality: "one", connectionPolicy: "replace", quickAdd: "capability", quickAddAfterConnected: false },
        { id: "document", label: "Document", type: "target", position: "bottom", style: "diamond", required: false, accepts: [{ capability: "document-source" }], allowedNodes: ["node:file-dataset", "node:text-dataset", "node:database-dataset"], cardinality: "many", connectionPolicy: "append", quickAdd: "capability", quickAddAfterConnected: true },
      ],
      style: {
        icon: "database-zap",
        iconColor: "var(--fabric-node-plugin-icon)",
        bgColor: "transparent",
        borderColor: "var(--fabric-node-border)",
      },
    },
    retriever: {
      type: "retriever",
      label: "Retriever",
      description: "Retrieve relevant context from a configured vector store.",
      category: "AI",
      role: "configuration",
      capabilities: ["retriever"],
      presentation: { base: "standard", rounded: "full" },
      handles: [{ id: "source", label: "", type: "source", position: "top", style: "diamond" }],
      style: {
        icon: "search",
        iconColor: "#65a30d",
        bgColor: "#f7fee7",
        borderColor: "#bef264",
      },
    },
    "basic-llm-chain": {
      type: "basic-llm-chain",
      label: "Basic LLM Chain",
      description: "Run a prompt through a chat model with optional structured output.",
      category: "AI",
      presentation: { base: "advanced", autoOrganize: true },
      handles: [
        { id: "model", label: "Model", type: "target", position: "bottom", style: "diamond", required: true, accepts: [{ capability: "chat-model" }], cardinality: "one", connectionPolicy: "replace", quickAdd: "capability" },
        { id: "outputParser", label: "Output Parser", type: "target", position: "bottom", style: "diamond", accepts: [{ capability: "output-parser" }], cardinality: "one", connectionPolicy: "replace", quickAdd: "capability", quickAddAfterConnected: true },
      ],
      style: { icon: "message-square-text", iconColor: "#2563eb", bgColor: "transparent", borderColor: "var(--fabric-node-border)" },
    },
    "structured-json-parser": {
      type: "structured-json-parser",
      label: "Structured JSON Parser",
      description: "Parse and validate model output against a JSON schema.",
      category: "AI",
      role: "configuration",
      capabilities: ["output-parser"],
      presentation: { base: "advanced", rounded: "full" },
      handles: [{ id: "source", label: "", type: "source", position: "top", style: "diamond" }],
      style: { icon: "braces", iconColor: "#db2777", bgColor: "#fdf2f8", borderColor: "#f9a8d4" },
    },
    "vector-store-retriever": {
      type: "vector-store-retriever",
      label: "Vector Store Retriever",
      description: "Expose a Vector Store as a reusable retriever.",
      category: "AI",
      role: "configuration",
      capabilities: ["retriever"],
      presentation: { base: "advanced", autoOrganize: true },
      handles: [
        { id: "source", label: "", type: "source", position: "top", style: "diamond" },
        { id: "vectorStore", label: "Vector Store", type: "target", position: "bottom", style: "diamond", required: true, accepts: [{ capability: "vector-store" }], cardinality: "one", connectionPolicy: "replace", quickAdd: "capability" },
      ],
      style: { icon: "search", iconColor: "#65a30d", bgColor: "#f7fee7", borderColor: "#bef264" },
    },
    "question-answer-chain": {
      type: "question-answer-chain",
      label: "Question and Answer Chain",
      description: "Answer a question with a chat model and retriever context.",
      category: "AI",
      presentation: { base: "advanced", autoOrganize: true },
      handles: [
        { id: "model", label: "Model", type: "target", position: "bottom", style: "diamond", required: true, accepts: [{ capability: "chat-model" }], cardinality: "one", connectionPolicy: "replace", quickAdd: "capability" },
        { id: "retriever", label: "Retriever", type: "target", position: "bottom", style: "diamond", required: true, accepts: [{ capability: "retriever" }], cardinality: "one", connectionPolicy: "replace", quickAdd: "capability" },
      ],
      style: { icon: "messages-square", iconColor: "#0891b2", bgColor: "transparent", borderColor: "var(--fabric-node-border)" },
    },
    "vector-store-tool": {
      type: "vector-store-tool",
      label: "Vector Store Tool",
      description: "Expose Vector Store retrieval as an Agent tool.",
      category: "AI",
      role: "configuration",
      capabilities: ["agent-tool"],
      presentation: { base: "advanced", autoOrganize: true, rounded: "full" },
      handles: [
        { id: "source", label: "Tool", type: "source", position: "top", style: "diamond" },
        { id: "vectorStore", label: "Vector Store", type: "target", position: "bottom", style: "diamond", required: true, accepts: [{ capability: "vector-store" }], cardinality: "one", connectionPolicy: "replace", quickAdd: "capability" },
        { id: "model", label: "Model", type: "target", position: "bottom", style: "diamond", required: true, accepts: [{ capability: "chat-model" }], cardinality: "one", connectionPolicy: "replace", quickAdd: "capability" },
      ],
      style: { icon: "database-zap", iconColor: "#ea580c", bgColor: "#fff7ed", borderColor: "#fdba74" },
    },
  },
});
