import type {
  Nod8Plugin,
  ApiKeyProvider,
  PluginManifest,
  PluginTriggerHooks,
  TriggerRegistrationContext,
} from "../../../shared/models/plugin-types.ts";
import manifest from "./manifest.json" with { type: "json" };
import { createTelegramMethods } from "./methods.ts";

// ──────────── ApiKey Provider ────────────
// Telegram uses a static Bot Token — no OAuth2 flow needed.
// The engine reads `type: "api_key"` and renders a simple credential form.

const auth: ApiKeyProvider = {
  type: "api_key",

  credentialSchema: {
    bot_token: {
      type: "string",
      inputType: "password",
      label: "Bot Token",
      description: "The token generated by @BotFather on Telegram. Format: 123456789:AAHxxxxxxxxxxxxxxxxxxxxxx",
      required: true,
      placeholder: "123456789:AAHxxxxxxxxxxxxxxxxxxxxxx",
    },
  },

  /**
   * Validates the provided token by calling the Telegram getMe endpoint.
   * Returns true if the token is valid and the bot is reachable.
   */
  async testConnection(credentials) {
    const token = credentials.bot_token?.trim();
    if (!token) {
      throw new Error("Bot token is missing or empty.");
    }

    const response = await fetch(`https://api.telegram.org/bot${token}/getMe`);
    const data = await response.json() as { ok: boolean; result?: { username: string } };

    if (!data.ok) {
      throw new Error("Invalid bot token — Telegram returned ok: false. Double-check the token from @BotFather.");
    }

    return true;
  },
};

// ──────────── Trigger Lifecycle Hooks ────────────
// The core engine calls setup() on publish and teardown() on unpublish/delete.
// This plugin is 100% responsible for knowing how to talk to Telegram's API.

const onMessageTrigger: PluginTriggerHooks = {
  async setup(ctx: TriggerRegistrationContext): Promise<void> {
    const token = ctx.credentials.bot_token?.trim();
    if (!token) {
      throw new Error("Telegram bot token is not configured. Please set credentials before publishing.");
    }

    // Build allowed_updates array from optional param
    const allowedTypesRaw = (ctx.params.allowedUpdateTypes as string | undefined)?.trim();
    const allowedUpdates = allowedTypesRaw
      ? allowedTypesRaw.split(",").map((t) => t.trim()).filter(Boolean)
      : [];

    const body: Record<string, any> = { url: ctx.webhookUrl };
    if (allowedUpdates.length > 0) {
      body.allowed_updates = allowedUpdates;
    }

    const response = await fetch(`https://api.telegram.org/bot${token}/setWebhook`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });

    const data = await response.json() as { ok: boolean; description?: string };

    if (!data.ok) {
      throw new Error(`Telegram setWebhook failed: ${data.description ?? "Unknown error"}`);
    }

    console.log(`[NOD8 | TELEGRAM]: Webhook registered at ${ctx.webhookUrl} for workflow '${ctx.workflowId}'`);
  },

  async teardown(ctx: TriggerRegistrationContext): Promise<void> {
    const token = ctx.credentials.bot_token?.trim();
    if (!token) return; // Nothing to clean up without a token

    const response = await fetch(`https://api.telegram.org/bot${token}/deleteWebhook`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ drop_pending_updates: false }),
    });

    const data = await response.json() as { ok: boolean; description?: string };

    if (!data.ok) {
      throw new Error(`Telegram deleteWebhook failed: ${data.description ?? "Unknown error"}`);
    }

    console.log(`[NOD8 | TELEGRAM]: Webhook unregistered for workflow '${ctx.workflowId}'`);
  },
};

// ──────────── Plugin Definition ────────────

const TelegramPlugin: Nod8Plugin = {
  id: "telegram",
  manifest: manifest as PluginManifest,
  auth,
  methods: createTelegramMethods(),
  triggers: {
    onMessage: onMessageTrigger,
  },
};

export default TelegramPlugin;
