import type {
  Nod8Plugin,
  ApiKeyProvider,
  PluginManifest,
} from "../../../shared/models/plugin-types.ts";
import manifest from "./manifest.json" with { type: "json" };
import { createTelegramMethods } from "./methods.ts";

// ──────────── ApiKey Provider ────────────
// Telegram uses a static Bot Token — no OAuth2 flow needed.
// The engine reads `type: "api_key"` and renders a simple credential form.

const auth: ApiKeyProvider = {
  type: "api_key",

  credentialSchema: {
    bot_token: {
      type: "string",
      inputType: "password",
      label: "Bot Token",
      description: "The token generated by @BotFather on Telegram. Format: 123456789:AAHxxxxxxxxxxxxxxxxxxxxxx",
      required: true,
      placeholder: "123456789:AAHxxxxxxxxxxxxxxxxxxxxxx",
    },
  },

  /**
   * Validates the provided token by calling the Telegram getMe endpoint.
   * Returns true if the token is valid and the bot is reachable.
   */
  async testConnection(credentials) {
    const token = credentials.bot_token?.trim();
    if (!token) {
      throw new Error("Bot token is missing or empty.");
    }

    const response = await fetch(`https://api.telegram.org/bot${token}/getMe`);
    const data = await response.json() as { ok: boolean; result?: { username: string } };

    if (!data.ok) {
      throw new Error("Invalid bot token — Telegram returned ok: false. Double-check the token from @BotFather.");
    }

    return true;
  },
};

// ──────────── Plugin Definition ────────────

const TelegramPlugin: Nod8Plugin = {
  id: "telegram",
  manifest: manifest as PluginManifest,
  auth,
  methods: createTelegramMethods(),
};

export default TelegramPlugin;
