import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import test from 'node:test'

const source = readFileSync(
  fileURLToPath(new URL('../WorkflowWorkbenchBottomPanel.vue', import.meta.url)),
  'utf8',
)

test('workflow bottom panel renders the selected view without internal tabs', () => {
  assert.match(source, /export type WorkflowBottomPanelView = 'timeline' \| 'tree' \| 'execution' \| 'variables'/)
  assert.match(source, /activeView === 'timeline'/)
  assert.match(source, /orderedTimelineNodes/)
  assert.match(source, /childIdsByParent/)
  assert.match(source, /parentIdsByChild/)
  assert.match(source, /rootByChild/)
  assert.match(source, /positionY/)
  assert.match(source, /columnById/)
  assert.match(source, /assignColumn/)
  assert.match(source, /placementsByColumn/)
  assert.match(source, /centerMergesFromParents/)
  assert.match(source, /centerSplitsFromChildren/)
  assert.match(source, /separateColumnCollisions/)
  assert.match(source, /normalizedLaneByValue/)
  assert.doesNotMatch(source, /lane: placement\.lane - minLane/)
  assert.match(source, /TIMELINE_COLORS/)
  assert.match(source, /TIMELINE_COLUMN_WIDTH/)
  assert.match(source, /TIMELINE_LANE_HEIGHT/)
  assert.match(source, /const TIMELINE_LANE_HEIGHT = 42/)
  assert.doesNotMatch(source, /TIMELINE_LEFT_GUTTER/)
  assert.match(source, /timelineConnectors/)
  assert.match(source, /timelineCursorIndex/)
  assert.match(source, /traceNodeIds/)
  assert.match(source, /selectTimelineNode/)
  assert.match(source, /focusTimelineNode/)
  assert.match(source, /hoverTimelineNode/)
  assert.match(source, /moveTimelineCursor/)
  assert.match(source, /handleTimelineKeydown/)
  assert.match(source, /isDraggingTimelinePlayhead/)
  assert.match(source, /timelinePlayheadDragX/)
  assert.match(source, /getTimelineSnapColumnFromClientX/)
  assert.match(source, /setTimelinePlayheadDragX/)
  assert.match(source, /getTimelinePlayheadDragClientX/)
  assert.match(source, /startTimelinePlayheadDrag/)
  assert.match(source, /handleTimelinePlayheadDrag/)
  assert.match(source, /stopTimelinePlayheadDrag/)
  assert.match(source, /onBeforeUnmount/)
  assert.match(source, /setTimelineCursorToDepth/)
  assert.match(source, /clearTimelineInteraction/)
  assert.doesNotMatch(source, /type="range"/)
  assert.match(source, /timelineDepthColumns/)
  assert.match(source, /timelineBranchLanes/)
  assert.match(source, /offsetFromRoot/)
  assert.match(source, /workflow-timeline__depth-grid/)
  assert.match(source, /workflow-timeline__depth-column/)
  assert.match(source, /workflow-timeline__lanes/)
  assert.match(source, /workflow-timeline__lane/)
  assert.match(source, /workflow-timeline__lane--root/)
  assert.match(source, /--workflow-timeline-lane-height/)
  assert.match(source, /\.workflow-timeline__lane\s*\{[\s\S]*\+ 11px \+ var\(--workflow-timeline-lane-y, 0px\)[\s\S]*height: var\(--workflow-timeline-lane-height, 42px\);[\s\S]*border-top: 1px solid[\s\S]*border-bottom: 1px solid/)
  assert.doesNotMatch(source, /\.workflow-timeline__lane::before/)
  assert.match(source, /workflow-timeline__playhead/)
  assert.match(source, /\.workflow-timeline__playhead\s*\{[\s\S]*top: 8px;[\s\S]*bottom: 0;/)
  assert.match(source, /\.workflow-timeline__playhead\s*\{[\s\S]*cursor: grab;[\s\S]*touch-action: none;/)
  assert.match(source, /\.workflow-timeline__playhead--dragging\s*\{[\s\S]*cursor: grabbing;[\s\S]*transition: none;/)
  assert.match(source, /\.workflow-timeline__playhead::before\s*\{[\s\S]*top: -5px;/)
  assert.match(source, /@pointerdown\.stop="startTimelinePlayheadDrag"/)
  assert.match(source, /window\.addEventListener\('pointermove', handleTimelinePlayheadDrag\)/)
  assert.match(source, /window\.addEventListener\('pointerup', stopTimelinePlayheadDrag, \{ once: true \}\)/)
  assert.match(source, /window\.addEventListener\('pointercancel', stopTimelinePlayheadDrag, \{ once: true \}\)/)
  assert.match(source, /window\.removeEventListener\('pointermove', handleTimelinePlayheadDrag\)/)
  assert.match(source, /window\.removeEventListener\('pointerup', stopTimelinePlayheadDrag\)/)
  assert.match(source, /window\.removeEventListener\('pointercancel', stopTimelinePlayheadDrag\)/)
  assert.match(source, /Math\.round\(\(clientX - rect\.left - TIMELINE_CONTENT_LEFT - 52\) \/ TIMELINE_COLUMN_WIDTH\)/)
  assert.match(source, /timelinePlayheadDragX\.value = Math\.min\(maxX, Math\.max\(minX, clientX - rect\.left\)\)/)
  assert.match(source, /const dragClientX = getTimelinePlayheadDragClientX\(\)/)
  assert.match(source, /workflow-timeline__plane/)
  assert.match(source, /<span[\s\S]*class="workflow-timeline__playhead"[\s\S]*@pointerdown\.stop="startTimelinePlayheadDrag"[\s\S]*\/>[\s\S]*<div class="workflow-timeline__depth-grid"[\s\S]*<div class="workflow-timeline__lanes"[\s\S]*<div class="workflow-timeline__plane" @click\.self="clearTimelineInteraction">/)
  assert.match(source, /workflow-timeline__connectors/)
  assert.match(source, /workflow-timeline__connector/)
  assert.match(source, /workflow-timeline__connector--passed/)
  assert.match(source, /`workflow-timeline__connector--\$\{connector\.status\}`/)
  assert.match(source, /workflow-timeline__duration/)
  assert.match(source, /workflow-timeline__tooltip/)
  assert.match(source, /position: fixed;/)
  assert.match(source, /workflow-timeline__clip--trace/)
  assert.match(source, /workflow-timeline__clip--dimmed/)
  assert.match(source, /@click="selectTimelineNode\(node\.id\)"/)
  assert.match(source, /@dblclick\.stop="focusTimelineNode\(node\.id\)"/)
  assert.match(source, /@keydown="handleTimelineKeydown"/)
  assert.doesNotMatch(source, /workflow-timeline__controls/)
  assert.doesNotMatch(source, /arrow-left/)
  assert.doesNotMatch(source, /arrow-right/)
  assert.match(source, /@click\.self="clearTimelineInteraction"/)
  assert.match(source, /@click\.stop="setTimelineCursorToDepth\(depth\.column\)"/)
  assert.match(source, /\.workflow-timeline__track\s*\{[\s\S]*user-select: none;/)
  assert.match(source, /\.workflow-timeline__connector--success\.workflow-timeline__connector--passed\s*\{[\s\S]*stroke: var\(--fabric-workflow-timeline-clip-success-border/)
  assert.match(source, /\.workflow-timeline__connector--failed\.workflow-timeline__connector--passed,[\s\S]*\.workflow-timeline__connector--cancelled\.workflow-timeline__connector--passed\s*\{[\s\S]*stroke: var\(--fabric-workflow-timeline-clip-error-border/)
  assert.match(source, /\.workflow-timeline__connector--waiting\.workflow-timeline__connector--passed,[\s\S]*\.workflow-timeline__connector--retrying\.workflow-timeline__connector--passed\s*\{[\s\S]*stroke: var\(--fabric-workflow-timeline-clip-waiting-border/)
  assert.match(source, /\.workflow-timeline__connector--running\.workflow-timeline__connector--passed\s*\{[\s\S]*stroke: var\(--fabric-workflow-timeline-clip-running-border/)
  assert.match(source, /\.workflow-timeline__clip--success\s*\{[\s\S]*outline: 2px solid/)
  assert.match(source, /\.workflow-timeline__clip--running\s*\{[\s\S]*outline: 2px solid/)
  assert.doesNotMatch(source, /\.workflow-timeline__clip--success\s*\{[^}]*border-color:/)
  assert.doesNotMatch(source, /\.workflow-timeline__clip--failed\s*\{[^}]*border-color:/)
  assert.doesNotMatch(source, /\.workflow-timeline__clip--running\s*\{[^}]*border-color:/)
  assert.match(source, /durationLabel/)
  assert.match(source, /--workflow-timeline-column-width/)
  assert.match(source, /--workflow-timeline-content-left/)
  assert.doesNotMatch(source, /--workflow-timeline-left-gutter/)
  assert.match(source, /background: transparent;/)
  assert.doesNotMatch(source, /\.workflow-timeline__depth-column\s*\{[^}]*linear-gradient/)
  assert.match(source, /--workflow-timeline-x/)
  assert.match(source, /--workflow-timeline-y/)
  assert.match(source, /--workflow-timeline-color/)
  assert.match(source, /iconForNodeType/)
  assert.match(source, /timelineStats/)
  assert.match(source, /panelTitle/)
  assert.match(source, /panelMeta/)
  assert.match(source, /emit\('close'\)/)
  assert.match(source, /\.workflow-bottom-panel__close:hover\s*\{[\s\S]*background-color: var\(--fabric-bg-muted\);/)
  assert.match(source, /\.workflow-timeline__stats code:not\(:last-child\)\s*\{[\s\S]*border-right: 1px solid var\(--fabric-border-muted\);/)
  assert.doesNotMatch(source, /\.workflow-timeline__stats\s*\{[^}]*margin-left: auto;/)
  assert.doesNotMatch(source, /\.workflow-timeline__stats\s*\{[^}]*border:/)
  assert.match(source, /scrollIntoView/)
  assert.match(source, /<ExecutionBottomPanel v-else-if="activeView === 'execution'"/)
  assert.match(source, /activeView === 'tree'/)
  assert.match(source, /v-else class="workflow-bottom-panel__view"/)
  assert.doesNotMatch(source, /workflow-bottom-panel__tabs/)
  assert.doesNotMatch(source, /workflow-bottom-panel__tab/)
  assert.doesNotMatch(source, /emit\('update:activeView'/)
  assert.doesNotMatch(source, /workflow-timeline__track::before/)
  assert.doesNotMatch(source, /workflow-timeline__clip::after/)
  assert.doesNotMatch(source, /'logs'/)
})
