import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import test from 'node:test'

const source = readFileSync(
  fileURLToPath(new URL('../WorkflowWorkbenchBottomPanel.vue', import.meta.url)),
  'utf8',
)

test('workflow bottom panel renders the selected view without internal tabs', () => {
  assert.match(source, /export type WorkflowBottomPanelView = 'timeline' \| 'tree' \| 'execution' \| 'variables'/)
  assert.match(source, /activeView === 'timeline'/)
  assert.match(source, /orderedTimelineNodes/)
  assert.match(source, /childIdsByParent/)
  assert.match(source, /parentIdsByChild/)
  assert.match(source, /rootByChild/)
  assert.match(source, /positionY/)
  assert.match(source, /columnById/)
  assert.match(source, /assignColumn/)
  assert.match(source, /placementsByColumn/)
  assert.match(source, /centerMergesFromParents/)
  assert.match(source, /centerSplitsFromChildren/)
  assert.match(source, /separateColumnCollisions/)
  assert.match(source, /TIMELINE_COLORS/)
  assert.match(source, /TIMELINE_COLUMN_WIDTH/)
  assert.match(source, /TIMELINE_LANE_HEIGHT/)
  assert.match(source, /const TIMELINE_LANE_HEIGHT = 42/)
  assert.doesNotMatch(source, /TIMELINE_LEFT_GUTTER/)
  assert.match(source, /timelineConnectors/)
  assert.match(source, /timelineDepthColumns/)
  assert.match(source, /timelineBranchLanes/)
  assert.match(source, /offsetFromRoot/)
  assert.match(source, /workflow-timeline__depth-grid/)
  assert.match(source, /workflow-timeline__depth-column/)
  assert.match(source, /workflow-timeline__lanes/)
  assert.match(source, /workflow-timeline__lane/)
  assert.match(source, /workflow-timeline__lane--root/)
  assert.match(source, /--workflow-timeline-lane-height/)
  assert.match(source, /\.workflow-timeline__lane\s*\{[\s\S]*height: var\(--workflow-timeline-lane-height, 42px\);/)
  assert.match(source, /\.workflow-timeline__lane::before\s*\{[\s\S]*top: 50%;[\s\S]*background: var\(--fabric-workflow-timeline-lane-border/)
  assert.match(source, /\.workflow-timeline__lane:last-child\s*\{[\s\S]*border-bottom: 1px solid/)
  assert.match(source, /workflow-timeline__playhead/)
  assert.match(source, /\.workflow-timeline__playhead\s*\{[\s\S]*top: 8px;[\s\S]*bottom: 0;/)
  assert.match(source, /\.workflow-timeline__playhead::before\s*\{[\s\S]*top: -5px;/)
  assert.match(source, /workflow-timeline__plane/)
  assert.match(source, /<span class="workflow-timeline__playhead" aria-hidden="true" \/>[\s\S]*<div class="workflow-timeline__depth-grid"[\s\S]*<div class="workflow-timeline__lanes"[\s\S]*<div class="workflow-timeline__plane">/)
  assert.match(source, /workflow-timeline__connectors/)
  assert.match(source, /workflow-timeline__connector/)
  assert.match(source, /workflow-timeline__connector--passed/)
  assert.match(source, /workflow-timeline__duration/)
  assert.match(source, /\.workflow-timeline__clip--success\s*\{[\s\S]*outline: 1px solid/)
  assert.match(source, /\.workflow-timeline__clip--running\s*\{[\s\S]*outline: 1px solid/)
  assert.doesNotMatch(source, /\.workflow-timeline__clip--success\s*\{[^}]*border-color:/)
  assert.doesNotMatch(source, /\.workflow-timeline__clip--failed\s*\{[^}]*border-color:/)
  assert.doesNotMatch(source, /\.workflow-timeline__clip--running\s*\{[^}]*border-color:/)
  assert.match(source, /durationLabel/)
  assert.match(source, /--workflow-timeline-column-width/)
  assert.match(source, /--workflow-timeline-content-left/)
  assert.doesNotMatch(source, /--workflow-timeline-left-gutter/)
  assert.match(source, /background: transparent;/)
  assert.doesNotMatch(source, /\.workflow-timeline__depth-column\s*\{[^}]*linear-gradient/)
  assert.match(source, /--workflow-timeline-x/)
  assert.match(source, /--workflow-timeline-y/)
  assert.match(source, /--workflow-timeline-color/)
  assert.match(source, /iconForNodeType/)
  assert.match(source, /timelineStats/)
  assert.match(source, /panelTitle/)
  assert.match(source, /panelMeta/)
  assert.match(source, /emit\('close'\)/)
  assert.match(source, /\.workflow-bottom-panel__close:hover\s*\{[\s\S]*background-color: var\(--fabric-bg-muted\);/)
  assert.match(source, /\.workflow-timeline__stats code:not\(:last-child\)\s*\{[\s\S]*border-right: 1px solid var\(--fabric-border-muted\);/)
  assert.doesNotMatch(source, /\.workflow-timeline__stats\s*\{[\s\S]*margin-left: auto;/)
  assert.doesNotMatch(source, /\.workflow-timeline__stats\s*\{[^}]*border:/)
  assert.match(source, /scrollIntoView/)
  assert.match(source, /<ExecutionBottomPanel v-else-if="activeView === 'execution'"/)
  assert.match(source, /activeView === 'tree'/)
  assert.match(source, /v-else class="workflow-bottom-panel__view"/)
  assert.doesNotMatch(source, /workflow-bottom-panel__tabs/)
  assert.doesNotMatch(source, /workflow-bottom-panel__tab/)
  assert.doesNotMatch(source, /emit\('update:activeView'/)
  assert.doesNotMatch(source, /workflow-timeline__track::before/)
  assert.doesNotMatch(source, /workflow-timeline__clip::after/)
  assert.doesNotMatch(source, /'logs'/)
})
